[workspace]
resolver = "2"

members = [
  "libDF",
  "pyDF",
  "pyDF-data",
  "ladspa",
#  "demo",
]

[profile.dev]
opt-level = 1
incremental = false
lto = false

[profile.release]
debug = true
opt-level = 3
lto = "thin"

[profile.release-lto]
inherits = "release"
lto = "fat"
panic = "abort"
